name: GitHub Snake

on:
  schedule:
    - cron: "0 */12 * * *"  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate Snake
      uses: Platane/snk@v3
      with:
        github_user_name: Milleny-pin
        github_token: ${{ secrets.GITHUB_TOKEN }}
        output_path: snake.svg
