name: Snake Game

on:
  schedule:
    - cron: "0 */12 * * *"  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Milleny-pin
          outputs: dist/snake.svg

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg
